<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE años [
    <!ELEMENT años (año_2021|año)*>
    <!ELEMENT año_2021 (trimestre|trimestre)*>
    <!ATTLIST año_2021
            año CDATA #REQUIRED>
    <!ELEMENT pedidos (pedido)*>
    <!ELEMENT pedido (nombre|apellidos|telefono|direccion|correo_electronico|fecha_inclusion|detalle_pedido)*>
    <!ELEMENT nombre (#PCDATA)>
    <!ELEMENT apellidos (#PCDATA)>
    <!ELEMENT telefono (#PCDATA)>
    <!ELEMENT direccion (calle|ciudad|codigo_postal|provincia)*>
    <!ELEMENT calle (#PCDATA)>
    <!ELEMENT ciudad (#PCDATA)>
    <!ELEMENT codigo_postal (#PCDATA)>
    <!ELEMENT provincia (#PCDATA)>
    <!ELEMENT correo_electronico (#PCDATA)>
    <!ELEMENT fecha_inclusion (#PCDATA)>
    <!ELEMENT detalle_pedido (numero_pedido|fecha_compra|fecha_entrega|total_factura|producto)*>
    <!ELEMENT numero_pedido (#PCDATA)>
    <!ELEMENT fecha_compra (#PCDATA)>
    <!ELEMENT fecha_entrega (#PCDATA)>
    <!ELEMENT total_factura (#PCDATA)>
    <!ELEMENT producto (nombre_producto|referencia|precio|unidades)*>
    <!ELEMENT nombre_producto (#PCDATA)>
    <!ELEMENT referencia (#PCDATA)>
    <!ELEMENT precio (#PCDATA)>
    <!ELEMENT unidades (#PCDATA)>
    <!ELEMENT trimestre (pedidos)*>
    <!ATTLIST trimestre
            trimestre CDATA #REQUIRED>
    <!ELEMENT año (trimestre)*>
    <!ATTLIST año
            año CDATA #REQUIRED>
]>
<años>
    <año año="2021">
        <trimestre trimestre="1">

            <pedidos>

                <pedido>
                    <nombre>Celia</nombre>
                    <apellidos>López Morate</apellidos>
                    <telefono>649 78 63 99</telefono>
                    <direccion>
                        <calle>Passeig Martos</calle>
                        <ciudad>Rosario Medio</ciudad>
                        <codigo_postal>29744</codigo_postal>
                        <provincia>Córdoba</provincia>
                    </direccion>
                    <correo_electronico>aponte.patricia@hispavista.com</correo_electronico>
                    <fecha_inclusion>3-12-2018</fecha_inclusion>
                    <detalle_pedido>
                        <numero_pedido>1</numero_pedido>
                        <fecha_compra>13-01-2021</fecha_compra>
                        <fecha_entrega>17-02-2021</fecha_entrega>
                        <total_factura>600 €</total_factura>
                        <producto>
                            <nombre_producto>Reloj inteligente</nombre_producto>
                            <referencia>RI3498</referencia>
                            <precio>200 €</precio>
                            <unidades>3</unidades>
                        </producto>
                    </detalle_pedido>
                </pedido>

                <pedido>
                    <nombre>María</nombre>
                    <apellidos>Mercedes Alvarez</apellidos>
                    <telefono>796 79 32 98</telefono>
                    <direccion>
                        <calle>Rúa Ona</calle>
                        <ciudad>Villa de las Torres</ciudad>
                        <codigo_postal>30314</codigo_postal>
                        <provincia>Badajoz</provincia>
                    </direccion>
                    <correo_electronico>jozuna@gmail.com</correo_electronico>
                    <fecha_inclusion>27-03-2020</fecha_inclusion>
                    <detalle_pedido>
                        <numero_pedido>2</numero_pedido>
                        <fecha_compra>12-01-2021</fecha_compra>
                        <fecha_entrega>05-03-2021</fecha_entrega>
                        <total_factura>130 €</total_factura>
                        <producto>
                            <nombre_producto>Botas de invierno</nombre_producto>
                            <referencia>BI7284</referencia>
                            <precio>130 €</precio>
                            <unidades>1</unidades>
                        </producto>
                    </detalle_pedido>
                </pedido>

                <pedido>
                    <nombre>Trini</nombre>
                    <apellidos>Esteve Alemán</apellidos>
                    <telefono>763 97 14 84</telefono>
                    <direccion>
                        <calle>Travessera Blanca</calle>
                        <ciudad>Gastélum de las Torres</ciudad>
                        <codigo_postal>77193</codigo_postal>
                        <provincia>Ávila</provincia>
                    </direccion>
                    <correo_electronico>bruno.monroy@otero.net</correo_electronico>
                    <fecha_inclusion>05-01-2019</fecha_inclusion>
                    <detalle_pedido>
                        <numero_pedido>3</numero_pedido>
                        <fecha_compra>05-02-2021</fecha_compra>
                        <fecha_entrega>09-03-2021</fecha_entrega>
                        <total_factura>450 €</total_factura>
                        <producto>
                            <nombre_producto>Cámara de acción</nombre_producto>
                            <referencia>CA1462</referencia>
                            <precio>150 €</precio>
                            <unidades>3</unidades>
                        </producto>
                    </detalle_pedido>
                </pedido>

                <pedido>
                    <nombre>Gil</nombre>
                    <apellidos>Amat Porras</apellidos>
                    <telefono>699 69 68 39</telefono>
                    <direccion>
                        <calle>Avinguda Sanz</calle>
                        <ciudad>Los Mascareñas de Lemos</ciudad>
                        <codigo_postal>57645</codigo_postal>
                        <provincia>Ciudad Real</provincia>
                    </direccion>
                    <correo_electronico>joel.merino@pacheco.es</correo_electronico>
                    <fecha_inclusion>07-07-2019</fecha_inclusion>
                    <detalle_pedido>
                        <numero_pedido>4</numero_pedido>
                        <fecha_compra>04-01-2021</fecha_compra>
                        <fecha_entrega>15-02-2021</fecha_entrega>
                        <total_factura>300 €</total_factura>
                        <producto>
                            <nombre_producto>Set de maletas</nombre_producto>
                            <referencia>SM9935</referencia>
                            <precio>300 €</precio>
                            <unidades>1</unidades>
                        </producto>
                    </detalle_pedido>
                </pedido>

                <pedido>
                    <nombre>Rufina</nombre>
                    <apellidos>Salas-Peiró</apellidos>
                    <telefono>644 07 15 60</telefono>
                    <direccion>
                        <calle>Praza Acuña</calle>
                        <ciudad>El Sauceda Baja</ciudad>
                        <codigo_postal>12591</codigo_postal>
                        <provincia>Toledo</provincia>
                    </direccion>
                    <correo_electronico>zmateo@gmail.com</correo_electronico>
                    <fecha_inclusion>13-09-2020</fecha_inclusion>
                    <detalle_pedido>
                        <numero_pedido>5</numero_pedido>
                        <fecha_compra>18-01-2021</fecha_compra>
                        <fecha_entrega>30-02-2021</fecha_entrega>
                        <total_factura>500 €</total_factura>
                        <producto>
                            <nombre_producto>Monitor de computadora</nombre_producto>
                            <referencia>MC2145</referencia>
                            <precio>250 €</precio>
                            <unidades>2</unidades>
                        </producto>
                    </detalle_pedido>
                </pedido>

                <pedido>
                    <nombre>Leire</nombre>
                    <apellidos>Montero-Llorens</apellidos>
                    <telefono>604 88 25 92</telefono>
                    <direccion>
                        <calle>Passeig Valentina</calle>
                        <ciudad>Varela del Pozo</ciudad>
                        <codigo_postal>57153</codigo_postal>
                        <provincia>Málaga</provincia>
                    </direccion>
                    <correo_electronico>mora.daniel@guerra.com</correo_electronico>
                    <fecha_inclusion>01-11-2020</fecha_inclusion>
                    <detalle_pedido>
                        <numero_pedido>6</numero_pedido>
                        <fecha_compra>26-01-2021</fecha_compra>
                        <fecha_entrega>18-03-2021</fecha_entrega>
                        <total_factura>100 €</total_factura>
                        <producto>
                            <nombre_producto>Auriculares Bluetooth</nombre_producto>
                            <referencia>AB8765</referencia>
                            <precio>50 €</precio>
                            <unidades>2</unidades>
                        </producto>
                    </detalle_pedido>
                </pedido>

                <pedido>
                    <nombre>Eva</nombre>
                    <apellidos>Rocamora Tudela</apellidos>
                    <telefono>774 14 06 89</telefono>
                    <direccion>
                        <calle>Plaza Alcaráz</calle>
                        <ciudad>A Ojeda del Penedès</ciudad>
                        <codigo_postal>67971</codigo_postal>
                        <provincia>Jaén</provincia>
                    </direccion>
                    <correo_electronico>francisco.muniz@hispavista.com</correo_electronico>
                    <fecha_inclusion>14-02-2017</fecha_inclusion>
                    <detalle_pedido>
                        <numero_pedido>7</numero_pedido>
                        <fecha_compra>26-01-2021</fecha_compra>
                        <fecha_entrega>22-02-2021</fecha_entrega>
                        <total_factura>150 €</total_factura>
                        <producto>
                            <nombre_producto>Camisa de algodón</nombre_producto>
                            <referencia>CA4521</referencia>
                            <precio>30 €</precio>
                            <unidades>5</unidades>
                        </producto>
                    </detalle_pedido>
                </pedido>

                <pedido>
                    <nombre>Edu</nombre>
                    <apellidos>Oliver Segovia</apellidos>
                    <telefono>639 38 11 16</telefono>
                    <direccion>
                        <calle>Camiño Ceja, 4, Bajos</calle>
                        <ciudad>Vall Iglesias de San Pedro</ciudad>
                        <codigo_postal>92646</codigo_postal>
                        <provincia>Burgos</provincia>
                    </direccion>
                    <correo_electronico>enrique16@yahoo.com</correo_electronico>
                    <fecha_inclusion>01-01-2021</fecha_inclusion>
                    <detalle_pedido>
                        <numero_pedido>8</numero_pedido>
                        <fecha_compra>17-01-2021</fecha_compra>
                        <fecha_entrega>17-03-2021</fecha_entrega>
                        <total_factura>450 €</total_factura>
                        <producto>
                            <nombre_producto>Aspiradora sin bolsa</nombre_producto>
                            <referencia>AS7392</referencia>
                            <precio>150 €</precio>
                            <unidades>3</unidades>
                        </producto>
                    </detalle_pedido>
                </pedido>

                <pedido>
                    <nombre>Josefa</nombre>
                    <apellidos>Águila Barbero</apellidos>
                    <telefono>641 13 82 52</telefono>
                    <direccion>
                        <calle>Praza Celia</calle>
                        <ciudad>A Velázquez de las Torres</ciudad>
                        <codigo_postal>28536</codigo_postal>
                        <provincia>Lugo</provincia>
                    </direccion>
                    <correo_electronico>miglesias@soto.org</correo_electronico>
                    <fecha_inclusion>15-02-2019</fecha_inclusion>
                    <detalle_pedido>
                        <numero_pedido>9</numero_pedido>
                        <fecha_compra>17-02-2021</fecha_compra>
                        <fecha_entrega>25-03-2021</fecha_entrega>
                        <total_factura>200 €</total_factura>
                        <producto>
                            <nombre_producto>Set de ollas y sartenes</nombre_producto>
                            <referencia>SO8910</referencia>
                            <precio>100 €</precio>
                            <unidades>2</unidades>
                        </producto>
                    </detalle_pedido>
                </pedido>

                <pedido>
                    <nombre>Olivia</nombre>
                    <apellidos>Ochoa Pedro</apellidos>
                    <telefono>695 86 74 56</telefono>
                    <direccion>
                        <calle>Passeig Ane</calle>
                        <ciudad>L' Gastélum</ciudad>
                        <codigo_postal>10543</codigo_postal>
                        <provincia>Huelva</provincia>
                    </direccion>
                    <correo_electronico>psandoval@live.com</correo_electronico>
                    <fecha_inclusion>19-01-2020</fecha_inclusion>
                    <detalle_pedido>
                        <numero_pedido>10</numero_pedido>
                        <fecha_compra>23-02-2021</fecha_compra>
                        <fecha_entrega>23-03-2021</fecha_entrega>
                        <total_factura>120 €</total_factura>
                        <producto>
                            <nombre_producto>Lámpara de mesa LED</nombre_producto>
                            <referencia>LM5264</referencia>
                            <precio>20 €</precio>
                            <unidades>6</unidades>
                        </producto>
                    </detalle_pedido>
                </pedido>

            </pedidos>

        </trimestre>

        <trimestre trimestre="2">

            <pedidos>

                <pedido>
                    <nombre>Celia</nombre>
                    <apellidos>López Morate</apellidos>
                    <telefono>649 78 63 99</telefono>
                    <direccion>
                        <calle>Passeig Martos</calle>
                        <ciudad>Rosario Medio</ciudad>
                        <codigo_postal>29744</codigo_postal>
                        <provincia>Córdoba</provincia>
                    </direccion>
                    <correo_electronico>aponte.patricia@hispavista.com</correo_electronico>
                    <fecha_inclusion>3-12-2018</fecha_inclusion>
                    <detalle_pedido>
                        <numero_pedido>11</numero_pedido>
                        <fecha_compra>31-04-2021</fecha_compra>
                        <fecha_entrega>15-05-2021</fecha_entrega>
                        <total_factura>180 €</total_factura>
                        <producto>
                            <nombre_producto>Mochila para portátil</nombre_producto>
                            <referencia>MP2045</referencia>
                            <precio>60 €</precio>
                            <unidades>3</unidades>
                        </producto>
                    </detalle_pedido>
                </pedido>

                <pedido>
                    <nombre>María</nombre>
                    <apellidos>Mercedes Alvarez</apellidos>
                    <telefono>796 79 32 98</telefono>
                    <direccion>
                        <calle>Rúa Ona</calle>
                        <ciudad>Villa de las Torres</ciudad>
                        <codigo_postal>30314</codigo_postal>
                        <provincia>Badajoz</provincia>
                    </direccion>
                    <correo_electronico>jozuna@gmail.com</correo_electronico>
                    <fecha_inclusion>27-03-2020</fecha_inclusion>
                    <detalle_pedido>
                        <numero_pedido>12</numero_pedido>
                        <fecha_compra>26-05-2021</fecha_compra>
                        <fecha_entrega>31-06-2021</fecha_entrega>
                        <total_factura>700 €</total_factura>
                        <producto>
                            <nombre_producto>Smart TV</nombre_producto>
                            <referencia>ST3461</referencia>
                            <precio>700 €</precio>
                            <unidades>1</unidades>
                        </producto>
                    </detalle_pedido>
                </pedido>

                <pedido>
                    <nombre>Trini</nombre>
                    <apellidos>Esteve Alemán</apellidos>
                    <telefono>763 97 14 84</telefono>
                    <direccion>
                        <calle>Travessera Blanca</calle>
                        <ciudad>Gastélum de las Torres</ciudad>
                        <codigo_postal>77193</codigo_postal>
                        <provincia>Ávila</provincia>
                    </direccion>
                    <correo_electronico>bruno.monroy@otero.net</correo_electronico>
                    <fecha_inclusion>05-01-2019</fecha_inclusion>
                    <detalle_pedido>
                        <numero_pedido>13</numero_pedido>
                        <fecha_compra>26-04-2021</fecha_compra>
                        <fecha_entrega>29-05-2021</fecha_entrega>
                        <total_factura>80 €</total_factura>
                        <producto>
                            <nombre_producto>Batidora de mano</nombre_producto>
                            <referencia>BH7298</referencia>
                            <precio>40 €</precio>
                            <unidades>2</unidades>
                        </producto>
                    </detalle_pedido>
                </pedido>

                <pedido>
                    <nombre>Gil</nombre>
                    <apellidos>Amat Porras</apellidos>
                    <telefono>699 69 68 39</telefono>
                    <direccion>
                        <calle>Avinguda Sanz</calle>
                        <ciudad>Los Mascareñas de Lemos</ciudad>
                        <codigo_postal>57645</codigo_postal>
                        <provincia>Ciudad Real</provincia>
                    </direccion>
                    <correo_electronico>joel.merino@pacheco.es</correo_electronico>
                    <fecha_inclusion>07-07-2019</fecha_inclusion>
                    <detalle_pedido>
                        <numero_pedido>14</numero_pedido>
                        <fecha_compra>13-05-2021</fecha_compra>
                        <fecha_entrega>01-06-2021</fecha_entrega>
                        <total_factura>180 €</total_factura>
                        <producto>
                            <nombre_producto>Kit de herramientas de 100 piezas</nombre_producto>
                            <referencia>KH8621</referencia>
                            <precio>90 €</precio>
                            <unidades>2</unidades>
                        </producto>
                    </detalle_pedido>
                </pedido>

                <pedido>
                    <nombre>Rufina</nombre>
                    <apellidos>Salas-Peiró</apellidos>
                    <telefono>644 07 15 60</telefono>
                    <direccion>
                        <calle>Praza Acuña</calle>
                        <ciudad>El Sauceda Baja</ciudad>
                        <codigo_postal>12591</codigo_postal>
                        <provincia>Toledo</provincia>
                    </direccion>
                    <correo_electronico>zmateo@gmail.com</correo_electronico>
                    <fecha_inclusion>13-09-2020</fecha_inclusion>
                    <detalle_pedido>
                        <numero_pedido>15</numero_pedido>
                        <fecha_compra>12-04-2021</fecha_compra>
                        <fecha_entrega>03-06-2021</fecha_entrega>
                        <total_factura>240 €</total_factura>
                        <producto>
                            <nombre_producto>Juego de edredón</nombre_producto>
                            <referencia>JE5174</referencia>
                            <precio>80 €</precio>
                            <unidades>3</unidades>
                        </producto>
                    </detalle_pedido>
                </pedido>

                <pedido>
                    <nombre>Natalia</nombre>
                    <apellidos>Aroca Amigó</apellidos>
                    <telefono>632 33 48 44</telefono>
                    <direccion>
                        <calle>Travessera Porras</calle>
                        <ciudad>San Mateos de Lemos</ciudad>
                        <codigo_postal>65129</codigo_postal>
                        <provincia>Ourense</provincia>
                    </direccion>
                    <correo_electronico>lucia22@herrera.com.es</correo_electronico>
                    <fecha_inclusion>28-03-2018</fecha_inclusion>
                    <detalle_pedido>
                        <numero_pedido>16</numero_pedido>
                        <fecha_compra>29-05-2021</fecha_compra>
                        <fecha_entrega>22-06-2021</fecha_entrega>
                        <total_factura>100 €</total_factura>
                        <producto>
                            <nombre_producto>Cafetera de cápsulas</nombre_producto>
                            <referencia>CC7284</referencia>
                            <precio>100 €</precio>
                            <unidades>1</unidades>
                        </producto>
                    </detalle_pedido>
                </pedido>

                <pedido>
                    <nombre>Emiliana</nombre>
                    <apellidos>Vilanova Cases</apellidos>
                    <telefono>733 34 01 65</telefono>
                    <direccion>
                        <calle>Ruela Fernández</calle>
                        <ciudad>Delgadillo del Mirador</ciudad>
                        <codigo_postal>79260</codigo_postal>
                        <provincia>Teruel</provincia>
                    </direccion>
                    <correo_electronico>collado.ariadna@live.com</correo_electronico>
                    <fecha_inclusion>16-12-2019</fecha_inclusion>
                    <detalle_pedido>
                        <numero_pedido>17</numero_pedido>
                        <fecha_compra>15-04-2021</fecha_compra>
                        <fecha_entrega>15-05-2021</fecha_entrega>
                        <total_factura>100 €</total_factura>
                        <producto>
                            <nombre_producto>Set de cuchillos de cocina</nombre_producto>
                            <referencia>SC9105</referencia>
                            <precio>50 €</precio>
                            <unidades>2</unidades>
                        </producto>
                    </detalle_pedido>
                </pedido>

                <pedido>
                    <nombre>Ágata</nombre>
                    <apellidos>Donaire Pinilla</apellidos>
                    <telefono>617 99 84 44</telefono>
                    <direccion>
                        <calle>Praza Andrea</calle>
                        <ciudad>Os Jáquez</ciudad>
                        <codigo_postal>37449</codigo_postal>
                        <provincia>Sevilla</provincia>
                    </direccion>
                    <correo_electronico>alejandro05@live.com</correo_electronico>
                    <fecha_inclusion>30-08-2019</fecha_inclusion>
                    <detalle_pedido>
                        <numero_pedido>18</numero_pedido>
                        <fecha_compra>06-04-2021</fecha_compra>
                        <fecha_entrega>23-04-2021</fecha_entrega>
                        <total_factura>300 €</total_factura>
                        <producto>
                            <nombre_producto>Auriculares con cancelación de ruido</nombre_producto>
                            <referencia>AC1427</referencia>
                            <precio>150 €</precio>
                            <unidades>2</unidades>
                        </producto>
                    </detalle_pedido>
                </pedido>

                <pedido>
                    <nombre>Dafne</nombre>
                    <apellidos>Pino-Corominas</apellidos>
                    <telefono>604 86 44 83</telefono>
                    <direccion>
                        <calle>Avinguda Alejandro</calle>
                        <ciudad>Sarabia de Arriba</ciudad>
                        <codigo_postal>14708</codigo_postal>
                        <provincia>La Rioja</provincia>
                    </direccion>
                    <correo_electronico>laura.peres@juan.net</correo_electronico>
                    <fecha_inclusion>21-06-2020</fecha_inclusion>
                    <detalle_pedido>
                        <numero_pedido>19</numero_pedido>
                        <fecha_compra>14-05-2021</fecha_compra>
                        <fecha_entrega>22-06-2021</fecha_entrega>
                        <total_factura>1000 €</total_factura>
                        <producto>
                            <nombre_producto>Silla de oficina ergonómica</nombre_producto>
                            <referencia>SO6952</referencia>
                            <precio>250 €</precio>
                            <unidades>4</unidades>
                        </producto>
                    </detalle_pedido>
                </pedido>

                <pedido>
                    <nombre>Vera</nombre>
                    <apellidos>López-Durán</apellidos>
                    <telefono>616 44 54 19</telefono>
                    <direccion>
                        <calle>Ronda Delgadillo</calle>
                        <ciudad>Villa Ordoñez</ciudad>
                        <codigo_postal>67842</codigo_postal>
                        <provincia>Huesca</provincia>
                    </direccion>
                    <correo_electronico>carla.luque@hotmail.com</correo_electronico>
                    <fecha_inclusion>18-03-2020</fecha_inclusion>
                    <detalle_pedido>
                        <numero_pedido>20</numero_pedido>
                        <fecha_compra>02-04-2021</fecha_compra>
                        <fecha_entrega>09-06-2021</fecha_entrega>
                        <total_factura>700 €</total_factura>
                        <producto>
                            <nombre_producto>Teléfono inteligente </nombre_producto>
                            <referencia>TI2236</referencia>
                            <precio>350 €</precio>
                            <unidades>2</unidades>
                        </producto>
                    </detalle_pedido>
                </pedido>

            </pedidos>

        </trimestre>

        <trimestre trimestre="3">

            <pedidos>

                <pedido>
                    <nombre>Celia</nombre>
                    <apellidos>López Morate</apellidos>
                    <telefono>649 78 63 99</telefono>
                    <direccion>
                        <calle>Passeig Martos</calle>
                        <ciudad>Rosario Medio</ciudad>
                        <codigo_postal>29744</codigo_postal>
                        <provincia>Córdoba</provincia>
                    </direccion>
                    <correo_electronico>aponte.patricia@hispavista.com</correo_electronico>
                    <fecha_inclusion>3-12-2018</fecha_inclusion>
                    <detalle_pedido>
                        <numero_pedido>21</numero_pedido>
                        <fecha_compra>30-07-2021</fecha_compra>
                        <fecha_entrega>14-08-2021</fecha_entrega>
                        <total_factura>140 €</total_factura>
                        <producto>
                            <nombre_producto>Altavoz Bluetooth portátil</nombre_producto>
                            <referencia>AB7681</referencia>
                            <precio>70 €</precio>
                            <unidades>2</unidades>
                        </producto>
                    </detalle_pedido>
                </pedido>

                <pedido>
                    <nombre>María</nombre>
                    <apellidos>Mercedes Alvarez</apellidos>
                    <telefono>796 79 32 98</telefono>
                    <direccion>
                        <calle>Rúa Ona</calle>
                        <ciudad>Villa de las Torres</ciudad>
                        <codigo_postal>30314</codigo_postal>
                        <provincia>Badajoz</provincia>
                    </direccion>
                    <correo_electronico>jozuna@gmail.com</correo_electronico>